name: land-atmosphere-interactions-and-hydrology-cookbook-dev
channels:
  - conda-forge
dependencies:
  - aiohttp
  - cmocean
  - easygems
  - healpix
  - intake==0.7.0
  - intake-esm
  - intake-stac
  - intake-xarray==0.7.0
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - uxarray
  - zarr<3.0.0
